#include "../../includes.hpp"

std::unordered_map<ID3v2AttachedPictureFrame::Type, const char*> MPEGMusicInternal::idv2PictureTypeDictionary = {
	{ ID3v2AttachedPictureFrame::Other, "Other" },
	{ ID3v2AttachedPictureFrame::FileIcon, "File Icon" },
	{ ID3v2AttachedPictureFrame::OtherFileIcon, "Other file icon" },
	{ ID3v2AttachedPictureFrame::FrontCover, "Cover (front)" },
	{ ID3v2AttachedPictureFrame::BackCover, "Cover (back)" },
	{ ID3v2AttachedPictureFrame::LeafletPage, "Leaflet page" },
	{ ID3v2AttachedPictureFrame::Media, "Media (e.g. lable side of CD)" },
	{ ID3v2AttachedPictureFrame::LeadArtist, "Lead artist/lead performer/soloist" },
	{ ID3v2AttachedPictureFrame::Artist, "Artist/performer" },
	{ ID3v2AttachedPictureFrame::Conductor, "Conductor" },
	{ ID3v2AttachedPictureFrame::Band, "Band/Orchestra" },
	{ ID3v2AttachedPictureFrame::Composer, "Composer" },
	{ ID3v2AttachedPictureFrame::Lyricist, "Lyricist/text writer" },
	{ ID3v2AttachedPictureFrame::RecordingLocation, "Recording Location" },
	{ ID3v2AttachedPictureFrame::DuringRecording, "During recording" },
	{ ID3v2AttachedPictureFrame::DuringPerformance, "During performance" },
	{ ID3v2AttachedPictureFrame::MovieScreenCapture, "Movie/video screen capture" },
	{ ID3v2AttachedPictureFrame::ColouredFish, "A bright coloured fish" },
	{ ID3v2AttachedPictureFrame::Illustration, "Illustration" },
	{ ID3v2AttachedPictureFrame::BandLogo, "Band/artist logotype" },
	{ ID3v2AttachedPictureFrame::PublisherLogo, "Publisher/Studio logotype" },
};

std::unordered_map<ID3v2EventTimingCodesFrame::EventType, const char*> MPEGMusicInternal::idv2EventTypeDictionary = {
	{ ID3v2EventTimingCodesFrame::Padding, "Padding" },
	{ ID3v2EventTimingCodesFrame::EndOfInitialSilence, "End Of Initial Silence" },
	{ ID3v2EventTimingCodesFrame::IntroStart, "Intro Start" },
	{ ID3v2EventTimingCodesFrame::MainPartStart, "Main Part Start" },
	{ ID3v2EventTimingCodesFrame::OutroStart, "Outro Start" },
	{ ID3v2EventTimingCodesFrame::OutroEnd, "Outro End" },
	{ ID3v2EventTimingCodesFrame::VerseStart, "Verse Start" },
	{ ID3v2EventTimingCodesFrame::RefrainStart, "Refrain Start" },
	{ ID3v2EventTimingCodesFrame::InterludeStart, "Interlude Start" },
	{ ID3v2EventTimingCodesFrame::ThemeStart, "Theme Start" },
	{ ID3v2EventTimingCodesFrame::VariationStart, "Variation Start" },
	{ ID3v2EventTimingCodesFrame::KeyChange, "Key Change" },
	{ ID3v2EventTimingCodesFrame::TimeChange, "Time Change" },
	{ ID3v2EventTimingCodesFrame::MomentaryUnwantedNoise, "Momentary Unwanted Noise" },
	{ ID3v2EventTimingCodesFrame::SustainedNoise, "Sustained Noise" },
	{ ID3v2EventTimingCodesFrame::SustainedNoiseEnd, "Sustained Noise End" },
	{ ID3v2EventTimingCodesFrame::IntroEnd, "Intro End" },
	{ ID3v2EventTimingCodesFrame::MainPartEnd, "Main Part End" },
	{ ID3v2EventTimingCodesFrame::VerseEnd, "Verse End" },
	{ ID3v2EventTimingCodesFrame::RefrainEnd, "Refrain End" },
	{ ID3v2EventTimingCodesFrame::ThemeEnd, "Theme End" },
	{ ID3v2EventTimingCodesFrame::Profanity, "Profanity" },
	{ ID3v2EventTimingCodesFrame::ProfanityEnd, "Profanity End" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch0, "Not Predefined Synch 0" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch1, "Not Predefined Synch 1" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch2, "Not Predefined Synch 2" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch3, "Not Predefined Synch 3" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch4, "Not Predefined Synch 4" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch5, "Not Predefined Synch 5" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch6, "Not Predefined Synch 6" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch7, "Not Predefined Synch 7" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch8, "Not Predefined Synch 8" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynch9, "Not Predefined Synch 9" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynchA, "Not Predefined Synch A" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynchB, "Not Predefined Synch B" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynchC, "Not Predefined Synch C" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynchD, "Not Predefined Synch D" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynchE, "Not Predefined Synch E" },
	{ ID3v2EventTimingCodesFrame::NotPredefinedSynchF, "Not Predefined Synch F" },
	{ ID3v2EventTimingCodesFrame::AudioEnd, "Audio End" },
	{ ID3v2EventTimingCodesFrame::AudioFileEnds, "Audio File Ends" },
};

std::unordered_map<ID3v2RelativeVolumeFrame::ChannelType, const char*> MPEGMusicInternal::idv2ChannelTypeDictionary = {
	{ ID3v2RelativeVolumeFrame::Other, "Other" },
	{ ID3v2RelativeVolumeFrame::MasterVolume, "Master Volume" },
	{ ID3v2RelativeVolumeFrame::FrontRight, "Front Right" },
	{ ID3v2RelativeVolumeFrame::FrontLeft, "Front Left" },
	{ ID3v2RelativeVolumeFrame::BackRight, "Back Right" },
	{ ID3v2RelativeVolumeFrame::BackLeft, "Back Left" },
	{ ID3v2RelativeVolumeFrame::FrontCentre, "Front Centre" },
	{ ID3v2RelativeVolumeFrame::BackCentre, "Back Centre" },
	{ ID3v2RelativeVolumeFrame::Subwoofer, "Subwoofer" },
};
